version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6380:6379"