version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - mongo
    environment:
      - PORT=80
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://mongo
#    volumes:
#      - ./:/home/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/data:/data/db
    ports:
      - "27018:27018"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
    volumes:
      - /home/redis/data:/data
