version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://mongo/
    volumes:
      - ./:/home/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/data:/data/db
#    command: mongod --port 27017
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"