version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"
      - "9222:9222"
    depends_on:
      - redis-cluster
      - mongo
    environment:
      - REDIS1_host=redis-cluster
      - REDIS1_port=7000
      - REDIS2_host=redis-cluster
      - REDIS2_port=7001
      - MONGO_URL=mongodb://mongo
    volumes:
      - ./:/home/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/data:/data/db
    ports:
      - "27017:27017"
  redis-cluster:
    container_name: redis-cluster
    image: "grokzen/redis-cluster"
    ports:
      - "7000-7005:7000-7005"