version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
    - "3001:3001"
    depends_on:
    - redis
    - mongo
    environment:
    - REDIS_URL=redis://redis
  mongo:
    container_name: mongo
    image: mongo
#    volumes:
#    - ./data:/data/db
    command: mongod --port 27018
    ports:
    - "27018:27018"
  redis:
    container_name: redis
    image: "redis"
    ports:
    - "6378:6378"