version: "3.7"
services:
  app:
    image: sirramin/mench
    restart: always
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - redis
      - mongo
    environment:
      - PORT=3005
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://mongo
#    volumes:
#      - ./:/home/app

  mongo:
    image: mongo
    ports:
      - "27018:27018"
#    volumes:
#      - /home/data:/data/db
#    deploy:
#      placement:
#        constraints: [node.role == manager]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
#    restart: always
#    volumes:
#      - /home/redis/data:/data
#    deploy:
#      placement:
#        constraints: [node.role == manager]