// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @constructor
 */
function signInAsGuest() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
}

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {signInAsGuest}
 */
signInAsGuest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {signInAsGuest=} obj
 * @returns {signInAsGuest}
 */
signInAsGuest.getRootAssignInAsGuest = function(bb, obj) {
  return (obj || new signInAsGuest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {signInAsGuest=} obj
 * @returns {signInAsGuest}
 */
signInAsGuest.getSizePrefixedRootAssignInAsGuest = function(bb, obj) {
  return (obj || new signInAsGuest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
signInAsGuest.prototype.token = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
signInAsGuest.prototype.username = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
signInAsGuest.startsignInAsGuest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tokenOffset
 */
signInAsGuest.addToken = function(builder, tokenOffset) {
  builder.addFieldOffset(0, tokenOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} usernameOffset
 */
signInAsGuest.addUsername = function(builder, usernameOffset) {
  builder.addFieldOffset(1, usernameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
signInAsGuest.endsignInAsGuest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
signInAsGuest.finishsignInAsGuestBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
signInAsGuest.finishSizePrefixedsignInAsGuestBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tokenOffset
 * @param {flatbuffers.Offset} usernameOffset
 * @returns {flatbuffers.Offset}
 */
signInAsGuest.createsignInAsGuest = function(builder, tokenOffset, usernameOffset) {
  signInAsGuest.startsignInAsGuest(builder);
  signInAsGuest.addToken(builder, tokenOffset);
  signInAsGuest.addUsername(builder, usernameOffset);
  return signInAsGuest.endsignInAsGuest(builder);
}

// Exports for Node.js and RequireJS
this.signInAsGuest = signInAsGuest;
