// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var MyGame = MyGame || {};

/**
 * @const
 * @namespace
 */
MyGame.Sample = MyGame.Sample || {};

/**
 * @constructor
 */
MyGame.Sample.ReposList = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {MyGame.Sample.ReposList}
 */
MyGame.Sample.ReposList.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {MyGame.Sample.ReposList=} obj
 * @returns {MyGame.Sample.ReposList}
 */
MyGame.Sample.ReposList.getRootAsReposList = function(bb, obj) {
  return (obj || new MyGame.Sample.ReposList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {MyGame.Sample.ReposList=} obj
 * @returns {MyGame.Sample.ReposList}
 */
MyGame.Sample.ReposList.getSizePrefixedRootAsReposList = function(bb, obj) {
  return (obj || new MyGame.Sample.ReposList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
MyGame.Sample.ReposList.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
MyGame.Sample.ReposList.startReposList = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
MyGame.Sample.ReposList.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
MyGame.Sample.ReposList.endReposList = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
MyGame.Sample.ReposList.finishReposListBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
MyGame.Sample.ReposList.finishSizePrefixedReposListBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 * @returns {flatbuffers.Offset}
 */
MyGame.Sample.ReposList.createReposList = function(builder, nameOffset) {
  MyGame.Sample.ReposList.startReposList(builder);
  MyGame.Sample.ReposList.addName(builder, nameOffset);
  return MyGame.Sample.ReposList.endReposList(builder);
}

// Exports for Node.js and RequireJS
this.MyGame = MyGame;
