// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Mench = Mench || {};

/**
 * @const
 * @namespace
 */
Mench.MatchMaking = Mench.MatchMaking || {};

/**
 * @constructor
 */
Mench.MatchMaking.obj = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Mench.MatchMaking.obj}
 */
Mench.MatchMaking.obj.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MatchMaking.obj=} obj
 * @returns {Mench.MatchMaking.obj}
 */
Mench.MatchMaking.obj.getRootAsobj = function(bb, obj) {
  return (obj || new Mench.MatchMaking.obj).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MatchMaking.obj=} obj
 * @returns {Mench.MatchMaking.obj}
 */
Mench.MatchMaking.obj.getSizePrefixedRootAsobj = function(bb, obj) {
  return (obj || new Mench.MatchMaking.obj).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
Mench.MatchMaking.obj.prototype.data = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Mench.MatchMaking.obj.startobj = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
Mench.MatchMaking.obj.addData = function(builder, dataOffset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Mench.MatchMaking.obj.endobj = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Mench.MatchMaking.obj.finishobjBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Mench.MatchMaking.obj.finishSizePrefixedobjBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 * @returns {flatbuffers.Offset}
 */
Mench.MatchMaking.obj.createobj = function(builder, dataOffset) {
  Mench.MatchMaking.obj.startobj(builder);
  Mench.MatchMaking.obj.addData(builder, dataOffset);
  return Mench.MatchMaking.obj.endobj(builder);
}

// Exports for Node.js and RequireJS
this.Mench = Mench;
