// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Mench = Mench || {};

/**
 * @const
 * @namespace
 */
Mench.MarblesPos = Mench.MarblesPos || {};

/**
 * @constructor
 */
Mench.MarblesPos.Marbs3 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Mench.MarblesPos.Marbs3}
 */
Mench.MarblesPos.Marbs3.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MarblesPos.Marbs3=} obj
 * @returns {Mench.MarblesPos.Marbs3}
 */
Mench.MarblesPos.Marbs3.getRootAsMarbs3 = function(bb, obj) {
  return (obj || new Mench.MarblesPos.Marbs3).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MarblesPos.Marbs3=} obj
 * @returns {Mench.MarblesPos.Marbs3}
 */
Mench.MarblesPos.Marbs3.getSizePrefixedRootAsMarbs3 = function(bb, obj) {
  return (obj || new Mench.MarblesPos.Marbs3).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Mench.MarblesPos.Marbs3.prototype.one = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Mench.MarblesPos.Marbs3.prototype.two = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Mench.MarblesPos.Marbs3.prototype.three = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Mench.MarblesPos.Marbs3.startMarbs3 = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} one
 */
Mench.MarblesPos.Marbs3.addOne = function(builder, one) {
  builder.addFieldInt16(0, one, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} two
 */
Mench.MarblesPos.Marbs3.addTwo = function(builder, two) {
  builder.addFieldInt16(1, two, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} three
 */
Mench.MarblesPos.Marbs3.addThree = function(builder, three) {
  builder.addFieldInt16(2, three, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Mench.MarblesPos.Marbs3.endMarbs3 = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} one
 * @param {number} two
 * @param {number} three
 * @returns {flatbuffers.Offset}
 */
Mench.MarblesPos.Marbs3.createMarbs3 = function(builder, one, two, three) {
  Mench.MarblesPos.Marbs3.startMarbs3(builder);
  Mench.MarblesPos.Marbs3.addOne(builder, one);
  Mench.MarblesPos.Marbs3.addTwo(builder, two);
  Mench.MarblesPos.Marbs3.addThree(builder, three);
  return Mench.MarblesPos.Marbs3.endMarbs3(builder);
}

/**
 * @constructor
 */
Mench.MarblesPos.MarblesPosition = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Mench.MarblesPos.MarblesPosition}
 */
Mench.MarblesPos.MarblesPosition.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MarblesPos.MarblesPosition=} obj
 * @returns {Mench.MarblesPos.MarblesPosition}
 */
Mench.MarblesPos.MarblesPosition.getRootAsMarblesPosition = function(bb, obj) {
  return (obj || new Mench.MarblesPos.MarblesPosition).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Mench.MarblesPos.MarblesPosition=} obj
 * @returns {Mench.MarblesPos.MarblesPosition}
 */
Mench.MarblesPos.MarblesPosition.getSizePrefixedRootAsMarblesPosition = function(bb, obj) {
  return (obj || new Mench.MarblesPos.MarblesPosition).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {Mench.MarblesPos.Marbs3=} obj
 * @returns {Mench.MarblesPos.Marbs3}
 */
Mench.MarblesPos.MarblesPosition.prototype.data = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new Mench.MarblesPos.Marbs3).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
Mench.MarblesPos.MarblesPosition.prototype.dataLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Mench.MarblesPos.MarblesPosition.startMarblesPosition = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
Mench.MarblesPos.MarblesPosition.addData = function(builder, dataOffset) {
  builder.addFieldOffset(0, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
Mench.MarblesPos.MarblesPosition.createDataVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Mench.MarblesPos.MarblesPosition.startDataVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Mench.MarblesPos.MarblesPosition.endMarblesPosition = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Mench.MarblesPos.MarblesPosition.finishMarblesPositionBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
Mench.MarblesPos.MarblesPosition.finishSizePrefixedMarblesPositionBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 * @returns {flatbuffers.Offset}
 */
Mench.MarblesPos.MarblesPosition.createMarblesPosition = function(builder, dataOffset) {
  Mench.MarblesPos.MarblesPosition.startMarblesPosition(builder);
  Mench.MarblesPos.MarblesPosition.addData(builder, dataOffset);
  return Mench.MarblesPos.MarblesPosition.endMarblesPosition(builder);
}

// Exports for Node.js and RequireJS
this.Mench = Mench;
